name: codespell

on:
    push:
      branches:
        - "*"
  
    pull_request_target:
      branches:
        - master


jobs:
  codespell:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup micromamba and install dependencies
        uses: mamba-org/setup-micromamba@v1
        with:
          environment-name: codespell-env
          create-args: >-
            python=3.x
            codespell

      - name: Run codespell
        run: |
          codespell
