#  For more information about TARDIS pipelines, please refer to:
#
#    https://tardis-sn.github.io/tardis/development/continuous_integration.html

name: release

on:
  schedule:
    - cron: "0 0 * * 0"
  workflow_dispatch: # manual trigger

defaults:
  run:
    shell: bash -l {0}


jobs:
  pip_tests:
    uses: ./.github/workflows/tests.yml
    secrets: inherit
    with:
      pip_git: true
  zenodo:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          repository: tardis-sn/tardis_zenodo
          token: ${{ secrets.BOT_TOKEN }}

      - name: Setup environment
        uses: tardis-sn/tardis-actions/setup-env@main
        with:
          os-label: "linux-64"

      - name: Dump Secret Key
        run: echo "$KEY_SECRET_JSON" > key_secret.json
        env:
          KEY_SECRET_JSON: ${{ secrets.ZENODO_KEY_SECRET_JSON }}

      - name: Run Notebook
        run: jupyter nbconvert gather_data.ipynb --to html --execute --ExecutePreprocessor.timeout=6000

      - name: Run Notebook (allow errors)
        run: jupyter nbconvert gather_data.ipynb --to html --execute --ExecutePreprocessor.timeout=6000 --allow-errors
        if: failure()

      - uses: actions/upload-artifact@v4
        with:
          name: zenodo_json
          path: .zenodo.json

