name: release

on:
  pull_request_target:
    branches: [master]
    types: [closed]

  workflow_dispatch: # manual trigger

jobs:
  create:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.x"

      - name: Install setuptools_scm
        run: pip install "setuptools_scm<7" git-cliff==2.6.1

      - name: Show current version
        run: python .ci-helpers/get_current_version.py

      - name: Get next version
        run: |
          python .ci-helpers/get_next_version.py
          echo "NEW_TAG=$(python .ci-helpers/get_next_version.py)" >> $GITHUB_ENV

      - name: Generate and process changelog
        run: |
          CHANGELOG=$(git cliff --config pyproject.toml --unreleased | sed -n '/^## Changelog/,$p' | grep -vE '^(ERROR|WARN)')
          echo "CHANGELOG<<EOF" >> $GITHUB_ENV
          echo "$CHANGELOG" >> $GITHUB_ENV
          echo "EOF" >> $GITHUB_ENV
        continue-on-error: true

      - name: Create new release
        id: create_release
        uses: softprops/action-gh-release@v1
        with:
          name: TARDIS v${{ env.NEW_TAG }}
          tag_name: release-${{ env.NEW_TAG }}
          body: |
            This release has been created automatically by the TARDIS continuous delivery pipeline.
            ${{ env.CHANGELOG }}
            A complete list of changes for this release is available at [CHANGELOG.md](https://github.com/tardis-sn/tardis/blob/master/CHANGELOG.md).
  
      - name: Fetch Latest DOI from Zenodo
        id: fetch-doi
        run: |
            CONCEPT_DOI="592480"
            response=$(curl -s "https://zenodo.org/api/records/${CONCEPT_DOI}")
            if echo "$response" | jq . >/dev/null 2>&1; then
              specific_doi=$(echo "$response" | jq -r '.id')
              doi_badge="![DOI](https://zenodo.org/badge/DOI/10.5281/zenodo.${specific_doi}.svg)"
              echo "doi_badge=${doi_badge}" >> $GITHUB_ENV
            else
              echo "Error: Invalid JSON response"
              echo "$response"
            fi
  
      - name: Update Changelog with Zenodo Badge
        run: |
          changelog_file="CHANGELOG.md"
          if [ -n "${{ env.doi_badge }}" ]; then
            sed -i "1i${{ env.doi_badge }}\n" "$changelog_file"
            echo "DOI badge added to CHANGELOG.md"
          else
            echo "Warning: DOI badge not available. Skipping changelog update."
          fi

      - name: Update release with DOI
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.ref_name }}
          body_path: CHANGELOG.md
          append_body: true