name: s tests

on:
  push:
    branches:
    - '*'
  pull_request:
    branches:
    - '*'
    
    types:
      - opened
      - reopened
      - synchronize
      - labeled

defaults:
  run:
    shell: bash -l {0}
 
jobs:
  build:
    strategy:
      matrix:
        label: [osx-arm64, linux-64]
        include:
          - label: osx-arm64
            os: macos-latest
            prefix: /Users/runner/miniconda3/envs/tardis

          - label: linux-64
            os: ubuntu-latest
            prefix: /usr/share/miniconda3/envs/tardis
    name: ${{ matrix.label }}
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4

      - name: Setup LFS
        uses: ./.github/actions/setup_lfs
      
      - name: Setup environment
        uses: ./.github/actions/setup_env
        with:
          os-label: ${{ matrix.label }}
      
      - uses: actions/checkout@v4
        with:
          repository: tardis-sn/stardis
      
      - name: Install TARDIS
        id: install-tardis
        run: |
          pip install git+https://github.com/tardis-sn/tardis.git
          
      - name: Install STARDIS
        id: install-stardis
        run: |
          pip install -e .[test]

      - name: Setup tmate session
        uses: mxschmitt/action-tmate@v3

      - name: Run Stardis tests  
        run: pytest

  
