name: Stardis Dispatch
on:
    push:
      branches:
        - master
    workflow_dispatch:

jobs:
  dispatch:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Dispatch to Stardis
        run: |
          curl -X POST \
            -H "Authorization: Bearer ${{ secrets.BOT_TOKEN }}" \
            -H "Accept: application/vnd.github+json" \
            -H "Content-Type: application/json" \
            -d '{ "event_type": "tardis-dispatch"}}' \
            https://api.github.com/repos/tardis-sn/stardis/dispatches
